 




Table users {
  user_id uuid [primary key]
  username string
  password string
  role string [note: 'attendee, employee, organizer, admin']
  created_at timestamp
}

Table user_profiles {
  user_profile_id uuid [primary key]
  user_id uuid [ref: - users.user_id] // aha ovo je zapr identifikaciona zavisnost!
  first_name string
  last_name string
  email string
  date_of_birth date
  profile_image_id uuid [ref: - images.image_id]
}



Table images {
  image_id uuid [primary key]
  url string // Stored in S3
}

Table festival_images {
  image_id uuid [ref: - images.image_id]
  festival_id uuid [ref: > festivals.festival_id]
}

Table addon_images {
  image_id uuid [ref: - images.image_id]
  addon_id uuid [ref: > pakage_addons.addon_id]
}



Table admins {
  admin_id uuid [primary key]
  user_id uuid [ref: - users.user_id]
}

Table attendees {
  attendee_id uuid [primary key]
  user_id uuid [ref: - users.user_id]
}

Table organizers {
  organizer_id uuid [primary key]
  user_id uuid [ref: - users.user_id]
}

Table employees {
  employee_id uuid [primary key]
  user_id uuid [ref: - users.user_id]
}



Table festivals {
  festival_id uuid [primary key]
  organizer_id uuid [ref: - organizers.organizer_id]
  name string
  description string
  start_date date
  end_date date
  capacity int
  status enum [note: 'public, private']
  store_status enum [note: 'open, closed']
}




Table ticket_types {
  ticket_type_id uuid [primary key]
  festival_id uuid [ref: > festivals.festival_id]
  name string
  description string
  price decimal
  available_number int // of tickets
  remaining_number int
}

Table pakage_addons {
  addon_id uuid [primary key]
  festival_id uuid [ref: > festivals.festival_id]
  name string
  description string
  category ENUM [note: 'general, transport, camp']
  price decimal
  available_number int
  remaining_number int
}

Table camp_addons {
  camp_addon_id uuid [primary key]
  addon_id uuid [ref: - pakage_addons.addon_id]
  camp_name string
  camp_image_id uuid [ref: - images.image_id]
}

Table camp_equipment {
  equipment_id uuid [primary key]
  camp_addon_id uuid [ref: > camp_addons.addon_id]
  name string
}

Table transport_addons {
  transport_addon_id uuid [primary key]
  addon_id uuid [ref: - pakage_addons.addon_id] // ovo ispada da je separate entity, a ne pod-tip addona?????

  departure_city_id uuid [ref: > cities.city_id]
  arrival_city_id uuid [ref: > cities.city_id]

  transport_type enum [note: 'plane, train, bus']
  
  departure_time datetime
  arrival_time datetime

  return_departure_time datetime
  return_arrival_time datetime
}

Table cities {
  city_id uuid [primary key]
  name uuid
  country_id uuid [ref: - countries.country_id]
}

Table countries {
  country_id uuid [primary key]
  name uuid
}





// THIS IS WHAT USER BUYS

Table festival_tickets {
  // user can buy festival ticket separately
  ticket_id uuid [primary key]
  ticket_type_id uuid [ref: > ticket_types.ticket_type_id]
  // Je l ovde onda cuvas i podatke o korisniku, o narukvici itd?
}

Table festival_packages {
  // user can buy a festival package that he created
  package_id uuid [primary key]
  festival_id uuid [ref: > festivals.festival_id]
}

Table festival_package_addons {
  package_id uuid [primary key, ref: > festival_packages.package_id]
  addon_id uuid [primary key, ref: < pakage_addons.addon_id]
}


// And finnaly, we can define purhcases Table

Table purchases {
  purchase_id uuid [primary key]
  attendee_id uuid [ref: - attendees.attendee_id]
  date date
  total_price decimal
}

Table package_purchase {
  package_purchase_id uuid [primary key]
  festival_package_id uuid [ref: - festival_packages.package_id]
}

Table ticket_purchase {
  ticket_purchase_id uuid [primary key]
  festival_ticket_id uuid [ref: - festival_tickets.ticket_id]
}
